"""
AC5 — Bernard voice completeness check.
Verifies YAML leaf keys are referenced in genjson.js and no forbidden phrases appear.
"""
import json
import yaml
import pytest
from pathlib import Path

ROOT = Path(__file__).parent.parent
COPY_YAML = ROOT / 'web/genjson/bernard_copy.yaml'
COPY_JSON = ROOT / 'web/genjson/bernard_copy.json'
GENJSON_JS = ROOT / 'web/genjson/genjson.js'

FORBIDDEN = [
    'most spaces leave this blank',
    'keep it simple',
    'you can do better',
    'well done',
    'great job',
]


def leaf_paths(d, prefix=''):
    for k, v in d.items():
        path = f"{prefix}.{k}" if prefix else k
        if isinstance(v, dict):
            yield from leaf_paths(v, path)
        else:
            yield path, v


def test_no_forbidden_patterns():
    copy = yaml.safe_load(COPY_YAML.read_text())
    for path, val in leaf_paths(copy):
        for forbidden in FORBIDDEN:
            assert forbidden.lower() not in val.lower(), \
                f"Forbidden pattern '{forbidden}' found at {path}"


def test_json_matches_yaml():
    """SSOT drift guard: the generated JSON must match the YAML source.

    bernard_copy.json is gitignored (a build artifact of `make bernard-copy`).
    The YAML is the single source of truth. This catches the failure mode where
    someone hand-edits the JSON, or the JSON goes stale after a YAML edit.

    A clean checkout has no JSON yet — skip (it'll be generated by deploy /
    `make bernard-copy`). When the JSON IS present, it must agree with the YAML.
    """
    if not COPY_JSON.exists():
        pytest.skip("bernard_copy.json not generated yet — run `make bernard-copy`")
    on_disk = json.loads(COPY_JSON.read_text())
    from_yaml = yaml.safe_load(COPY_YAML.read_text())
    assert on_disk == from_yaml, (
        "bernard_copy.json is out of sync with bernard_copy.yaml. "
        "The YAML is the source of truth — run `make bernard-copy` to regenerate. "
        "Never hand-edit the JSON."
    )


def test_keys_referenced_in_js():
    js = GENJSON_JS.read_text()
    copy = yaml.safe_load(COPY_YAML.read_text())
    unreferenced = []
    for path, _ in leaf_paths(copy):
        parts = path.split('.')
        dotted = 'COPY.' + path
        bracketed = 'COPY' + ''.join(f"['{p}']" for p in parts)
        if dotted not in js and bracketed not in js:
            unreferenced.append(path)
    if unreferenced:
        print(f"\nWARN: YAML keys not yet referenced in genjson.js: {unreferenced}")
    # warn-only: future stories add keys before JS uses them
